def ohe_colnames():
    col_names = ['workclass_ Federal-gov', 'workclass_ Local-gov', 'workclass_ Never-worked', 'workclass_ Private',
                 'workclass_ Self-emp-inc', 'workclass_ Self-emp-not-inc', 'workclass_ State-gov',
                 'workclass_ Without-pay',
                 'workclass_nan', 'education_ 10th', 'education_ 11th', 'education_ 12th', 'education_ 1st-4th',
                 'education_ 5th-6th', 'education_ 7th-8th', 'education_ 9th', 'education_ Assoc-acdm',
                 'education_ Assoc-voc',
                 'education_ Bachelors', 'education_ Doctorate', 'education_ HS-grad', 'education_ Masters',
                 'education_ Preschool', 'education_ Prof-school', 'education_ Some-college',
                 'marital-status_ Divorced',
                 'marital-status_ Married-AF-spouse', 'marital-status_ Married-civ-spouse',
                 'marital-status_ Married-spouse-absent', 'marital-status_ Never-married', 'marital-status_ Separated',
                 'marital-status_ Widowed', 'occupation_ Adm-clerical', 'occupation_ Armed-Forces',
                 'occupation_ Craft-repair',
                 'occupation_ Exec-managerial', 'occupation_ Farming-fishing', 'occupation_ Handlers-cleaners',
                 'occupation_ Machine-op-inspct', 'occupation_ Other-service', 'occupation_ Priv-house-serv',
                 'occupation_ Prof-specialty', 'occupation_ Protective-serv', 'occupation_ Sales',
                 'occupation_ Tech-support',
                 'occupation_ Transport-moving', 'occupation_nan', 'relationship_ Husband',
                 'relationship_ Not-in-family',
                 'relationship_ Other-relative', 'relationship_ Own-child', 'relationship_ Unmarried',
                 'relationship_ Wife',
                 'race_ Amer-Indian-Eskimo', 'race_ Asian-Pac-Islander', 'race_ Black', 'race_ Other', 'race_ White',
                 'sex_ Female', 'sex_ Male', 'native_country_ Cambodia', 'native_country_ Canada',
                 'native_country_ China',
                 'native_country_ Columbia', 'native_country_ Cuba', 'native_country_ Dominican-Republic',
                 'native_country_ Ecuador', 'native_country_ El-Salvador', 'native_country_ England',
                 'native_country_ France',
                 'native_country_ Germany', 'native_country_ Greece', 'native_country_ Guatemala',
                 'native_country_ Haiti',
                 'native_country_ Holand-Netherlands', 'native_country_ Honduras', 'native_country_ Hong',
                 'native_country_ Hungary', 'native_country_ India', 'native_country_ Iran', 'native_country_ Ireland',
                 'native_country_ Italy', 'native_country_ Jamaica', 'native_country_ Japan', 'native_country_ Laos',
                 'native_country_ Mexico', 'native_country_ Nicaragua', 'native_country_ Outlying-US(Guam-USVI-etc)',
                 'native_country_ Peru', 'native_country_ Philippines', 'native_country_ Poland',
                 'native_country_ Portugal',
                 'native_country_ Puerto-Rico', 'native_country_ Scotland', 'native_country_ South',
                 'native_country_ Taiwan',
                 'native_country_ Thailand', 'native_country_ Trinadad&Tobago', 'native_country_ United-States',
                 'native_country_ Vietnam', 'native_country_ Yugoslavia', 'native_country_nan', 'age', 'fnlwgt',
                 'education_num',
                 'capital_gain', 'capital_loss', 'hours_per_week']

    return col_names